### ISSUE TITLE
Removing a quantity restriction for a product doesn't remove its settings from the database

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/uc_restrict_qty#2]
Steps to reproduce:

1. Create a product
2. Visit "Features" and add a quantity restriction. It's created normally and the settings are stored in table `uc_restrict_qty_products` 👍🏽 
3. Delete the quantity restriction feature for the product
4. Check the content of table `uc_restrict_qty_products`. The settings are not removed. 
5. Try creating a new restriction for the product. You'll get `A quantity restriction has already been set up for this SKU` even though none is listed in the UI

PR coming

**Comment by argiepiano** [comment]
BTW the issue is that `uc_product_feature_delete()` invokes the delete feature callback with $pfid as argument, NOT the full feature object.

**Comment by argiepiano** [comment]
PR #3 ready for review

**Comment by argiepiano** [comment]
Hi @laryn 😁 Let me know if you want to take a look before I merge. I tested pretty intensely 👍🏽

**Comment by laryn** [comment]
No, I say merge!
