### ISSUE TITLE
Module settings are not saved

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/uc_restrict_qty#4]
To reproduce:

1. Visit `admin/store/settings/products`
2. Select `Restrict Qty settings` in the vertical tab
3. Enter some values for the settings
4. Click Save

The settings are not saved.

**Comment by argiepiano** [comment]
PR #5 ready for testing.

Because this is a subform for the Products settings system config form, and because the parent form doesn't contain a `[#config]` element, setting a `#config` element for the subform doesn't work as expected (see explanation of this behavior [here](https://docs.backdropcms.org/api/backdrop/core%21modules%21system%21system.module/function/system_settings_form/1)).

Therefore we need to create a submit handler and manually save the 4 settings to `uc_restrict_qty.settings`.

**Comment by argiepiano** [comment]
@laryn, let me know if you'd like to take a look before I merge

**Comment by laryn** [comment]
@argiepiano I glanced at the code and I'm okay with you moving ahead. (Also there are currently only 3 active sites using this module).
